#!/bin/sh
tmpfile=cred
role=$1
shift
aws sts assume-role --role-arn $role --role-session-name assumerole > $tmpfile
export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId < $tmpfile)
export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey < $tmpfile)
export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken < $tmpfile)
rm $tmpfile
aws $*
