#!/bin/sh

ko=0
if [ ! "$EKS_NAME" ]
then
  ko=1
  echo "You must set the EKS_NAME environment variable to the name of the EKS cluster"
fi

if [ ! "$AWS_ASSUME_ROLE" ]
then
  ko=1
  echo "You must set the AWS_ASSUME_ROLE environment variable to the ARN of the role to assume"
fi

if [ "$ko" -eq 1 ]
then
  exit 1
fi

if [ ! "$AWS_DEFAULT_REGION" ]
then
  export AWS_DEFAULT_REGION=eu-west-1
fi

assume_role $AWS_ASSUME_ROLE eks update-kubeconfig --name=$EKS_NAME --role-arn $AWS_ASSUME_ROLE
